### ISSUE TITLE
npm install goes error

### ISSUE THREAD

**Issue by ZCC1** [Chatie/wechaty-getting-started#33]
node version  - 10.6.0
platform - win10

I follow the instructions   to get start.
when I "npm config set registry https://github.com/Chatie/wechaty/wiki/NPM#use-npm-in-china" and run 'npm install' . I got a lot of errors.I put those errors at the end of this issues.
so I do 'npm config set registry https://registry.npm.taobao.org' and run 'npm install' ,everything gose right

I do not know why, someone help me ?

Below is the error detail
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install' ]
2 info using npm@6.1.0
3 info using node@v10.6.0
4 verbose npm-session 63d543a1f2b947a9
5 silly install runPreinstallTopLevelLifecycles
6 silly preinstall wechaty-getting-started@0.1.0
7 info lifecycle wechaty-getting-started@0.1.0~preinstall: wechaty-getting-started@0.1.0
8 silly install loadCurrentTree
9 silly install readLocalPackageData
10 timing stage:loadCurrentTree Completed in 16ms
11 silly install loadIdealTree
12 silly install cloneCurrentTreeToIdealTree
13 timing stage:loadIdealTree:cloneCurrentTree Completed in 0ms
14 silly install loadShrinkwrap
15 timing stage:loadIdealTree:loadShrinkwrap Completed in 4ms
16 silly install loadAllDepsIntoIdealTree
17 http fetch GET 200 https://github.com/Chatie/wechaty/wiki/qrcode-terminal 3791ms
18 silly fetchPackageMetaData error for qrcode-terminal@^0.12.0 Unexpected token < in JSON at position 6 while parsing near '
18 silly fetchPackageMetaData
18 silly fetchPackageMetaData
18 silly fetchPackageMetaData
18 silly fetchPackageMetaData
18 silly fetchPackageMetaData
18 silly fetchPackageMetaData <!DOCTYPE html>
18 silly fetchPackageMetaData <htm...'
19 http fetch GET 200 https://github.com/Chatie/wechaty/wiki/wechaty 3943ms
20 silly fetchPackageMetaData error for wechaty@^0.19.1 Unexpected token < in JSON at position 6 while parsing near '
20 silly fetchPackageMetaData
20 silly fetchPackageMetaData
20 silly fetchPackageMetaData
20 silly fetchPackageMetaData
20 silly fetchPackageMetaData
20 silly fetchPackageMetaData <!DOCTYPE html>
20 silly fetchPackageMetaData <htm...'
21 http fetch GET 200 https://github.com/Chatie/wechaty/wiki/qrcode-terminal 2023ms
22 silly fetchPackageMetaData error for qrcode-terminal@^0.12.0 Unexpected token < in JSON at position 6 while parsing near '
22 silly fetchPackageMetaData
22 silly fetchPackageMetaData
22 silly fetchPackageMetaData
22 silly fetchPackageMetaData
22 silly fetchPackageMetaData
22 silly fetchPackageMetaData <!DOCTYPE html>
22 silly fetchPackageMetaData <htm...'
23 http fetch GET 200 https://github.com/Chatie/wechaty/wiki/wechaty 2728ms
24 silly fetchPackageMetaData error for wechaty@^0.19.1 Unexpected token < in JSON at position 6 while parsing near '
24 silly fetchPackageMetaData
24 silly fetchPackageMetaData
24 silly fetchPackageMetaData
24 silly fetchPackageMetaData
24 silly fetchPackageMetaData
24 silly fetchPackageMetaData <!DOCTYPE html>
24 silly fetchPackageMetaData <htm...'
25 timing stage:rollbackFailedOptional Completed in 0ms
26 timing stage:runTopLevelLifecycles Completed in 7238ms
27 silly saveTree wechaty-getting-started@0.1.0
28 verbose stack SyntaxError: Unexpected token < in JSON at position 6 while parsing near '
28 verbose stack
28 verbose stack
28 verbose stack
28 verbose stack
28 verbose stack
28 verbose stack <!DOCTYPE html>
28 verbose stack <htm...'
28 verbose stack     at JSON.parse (<anonymous>)
28 verbose stack     at parseJson (C:\Program Files\nodejs\node_modules\npm\node_modules\json-parse-better-errors\index.js:7:17)
28 verbose stack     at consumeBody.call.then.buffer (C:\Program Files\nodejs\node_modules\npm\node_modules\node-fetch-npm\src\body.js:96:50)
28 verbose stack     at process._tickCallback (internal/process/next_tick.js:68:7)
29 verbose cwd C:\work\develop\node\wechaty-getting-started
30 verbose Windows_NT 10.0.17134
31 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
32 verbose node v10.6.0
33 verbose npm  v6.1.0
34 error Unexpected token < in JSON at position 6 while parsing near '
34 error
34 error
34 error
34 error
34 error
34 error <!DOCTYPE html>
34 error <htm...'
35 verbose exit [ 1, true ]

**Comment by zixia** [comment]
Please have a look at <https://ci.appveyor.com/project/chatie/wechaty-getting-started>, it seems this repository can work under win32 without any problem.

**Comment by ZCC1** [comment]
Thanks ,Actually my computer is win10 64bit.

**Comment by ZCC1** [comment]
yes, I do, but also thank for you help.

**Comment by ZCC1** [comment]
yes, I do, but also thank for you help.

**Comment by zixia** [comment]
Glad to hear that, congratulations!
