### ISSUE TITLE
media-file-bot save file to local not work

### ISSUE THREAD

**Issue by 3014zhangshuo** [Chatie/wechaty-getting-started#38]
Hi,
I clone `Chatie/wechaty-getting-started` and `Chatie/wechaty`, run the media-file-bot example with two projects, but when I send a pdf file to the robot，file save not be trigger `msg.type() !== bot.Message.Type.Text` will be return false, only return something like this `RECV: Message#Text(🗣Contact<张硕>👤Contact<WonderCV小助手>)<&lt;msg&gt;&lt;appmsg appid="" sdkver="0"&gt;&lt;title&gt;xxx.pdf&lt;/>`.

I also clone `lijiarui/wechaty-puppet-padchat` add the code to `examples/wechaty-padchat-bot` onMessage function 
```
  if (msg.type() !== Message.Type.Text) {
    const file = await msg.toFileBox()
    const name = file.name
     console.log('Save file to: ' + name)
     file.toFile(name)
  }
```
I try again that console throw `unsupport type: StatusNotify(51) because it is not fully implemented yet`

Does this mean that the feature is not yet supported? , or is there a problem with the version I am running? Three projects are cloned master branch.
I look forward to your answer.  thank you .

**Comment by 3014zhangshuo** [comment]
I forget `rm -f package-lock.json`. I will try to reinstall dependencies first.

**Comment by zixia** [comment]
Yes, save the attachment to file is not fully implementated by PuppetPadchat. 

See: https://github.com/lijiarui/wechaty-puppet-padchat/issues/101

**Comment by zixia** [comment]
BTW: If you want to download those files and do not care about which puppet you are using, then you can try `puppeteer`, it supports download almost all kinds of the attachments.

Start Wechaty with `WECHATY_PUPPET=puppeteer` to use PuppetPuppeteer.

**Comment by 3014zhangshuo** [comment]
Thank you for your answer，but i want use`PuppetPadchat ` to broke wechat limitations，Looking forward to perfecting this feature.

**Comment by zixia** [comment]
You are welcome.

Please close this issue if there are no other questions, have a nice day!
