### ISSUE TITLE
Not working on Ubuntu 16.04.4 LTS

### ISSUE THREAD

**Issue by Chlerry** [Chatie/wechaty-getting-started#39]
As the document recommended, I purchased a server on Digital Ocean to run this demo. I chose an Ubuntu 16.04.4 LTS image and updated the Node.js version on it; However, something wrong still occurred. I attach the output from my command line here in case someone needs to look it up. 
[Terminal Saved Output.txt](https://github.com/Chatie/wechaty-getting-started/files/2206383/Terminal.Saved.Output.txt)

**Comment by Chlerry** [comment]
I tried Debian GNU/Linux 9.5 this time... still the same error

**Comment by Chlerry** [comment]
Issue solved by installing NPM dependencies and Chromium.

**Comment by zixia** [comment]
Can you share the commands that fix the problem in your case?

**Comment by Chlerry** [comment]
I think these are the commands: 
```sh
sudo apt-get install -y nodejs
sudo apt-get install gcc g++ make
sudo apt-get install -y build-essential
npm install brolog
sudo apt-get install libx11-xcb1
sudo apt-get install chromium-browser
```
